---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-1001
spec:
  config: '{
  "cniVersion": "0.4.0",
  "name": "ipvlan-1001",
  "plugins": [{
    "type": "ipvlan",
    "master": "VLAN-1001",
    "ipam": {
      "type": "static",
      "addresses": [
          { 
	      "address": "10.7.4.20/24"              
          }
        ],
      "routes": [ 
        { 
          "dst": "0.0.0.0/0", 
          "gw": "10.7.4.1" 
        } 
      ]
    }
  }]
}'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-1002
spec:
  config: '{
  "cniVersion": "0.4.0",
  "name": "ipvlan-1002",
  "plugins": [{
    "type": "ipvlan",
    "master": "VLAN-1002",
    "ipam": {
      "type": "static",
      "addresses": [
          {
              "address": "10.7.10.20/24"
          }
        ],
      "routes": [
        {
          "dst": "0.0.0.0/0",
          "gw": "10.7.10.1"
        }
      ]      
    }
  }]
}'
